
create database FileSheild;
use FileSheild;

CREATE TABLE users (
    id CHAR(36) PRIMARY KEY DEFAULT (UUID()),
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    is_verified BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


ALTER TABLE users ADD COLUMN auth_token VARCHAR(255);

ALTER TABLE users MODIFY password VARCHAR(255) NULL;

ALTER TABLE users ADD COLUMN google_id VARCHAR(255) NULL UNIQUE;

ALTER TABLE users ADD COLUMN provider VARCHAR(50) DEFAULT 'local';


ALTER TABLE users 
ADD reset_token VARCHAR(255),
ADD reset_expiry DATETIME;